name: showcase_view
description: Showcase View module.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_markdown: ^0.6.0
  source_code_view:
    path: ../source_code_view

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  pedantic:

flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.example.showcase_view
    iosBundleIdentifier: com.example.showcaseView
