name: flutter_widgets_explorer
description: Flutter Widgets Explorer project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  buttons_tabbar: ^1.1.1
  trading_chart: ^0.1.2
  http: ^0.12.2
  charts_flutter: ^0.9.0
  google_sign_in: ^4.5.9
  flutter_facebook_login: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/stock_chart/depth.json
    - assets/chart_datatable/quarterly_result.json
