name: flutter_widgets_explorer
description: Flutter Widgets Explorer project.

publish_to: "none"

version: 0.3.6

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_modular: ^3.0.2+1
  cupertino_icons: ^1.0.0
  buttons_tabbar: ^1.1.1
  trading_chart: ^0.1.2
  http: ^0.13.0
  charts_flutter: ^0.9.0
  flutter_syntax_view: ^3.2.2
  animate_icons: ^1.0.0
  url_launcher: ^6.0.2
  flutter_markdown: ^0.6.0
  shimmer: ^1.1.2
  package_info_plus: ^1.0.0
  pubspec_parse: ^1.0.0
  source_code_view:
    path: source_code_view
  showcase_view:
    path: showcase_view    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^1.0.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "dev_assets/images/icon_white_bg.png"

flutter_native_splash:
  color: "#ffffff"
  image: dev_assets/images/icon_white_bg.png
  color_dark: "#000000"
  image_dark: dev_assets/images/icon_black_bg.png
  fullscreen: true

flutter:
  uses-material-design: true
  assets:
    - assets/stock_chart/depth.json
    - assets/chart_datatable/quarterly_result.json
    - assets/shimmer/images/chevron_right.png
    - assets/shimmer/images/background.jpg
    - assets/about/images/logo_bright.png

scripts:
  record: adb shell screenrecord --size 324x576 /sdcard/recording.mp4
  pull_recording: adb pull /sdcard/recording.mp4
  convert_mp4_to_gif: ./gifify.sh recording.mp4

