name: flutter_widgets_explorer
description: Flutter Widgets Explorer project.

publish_to: "none"

version: 0.3.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  buttons_tabbar: ^1.1.1
  trading_chart: ^0.1.2
  http: ^0.12.2
  charts_flutter: ^0.9.0
  flutter_syntax_view: ^3.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1
  flutter_native_splash: ^0.3.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "dev_assets/images/icon_white_bg.png"

flutter_native_splash:
  color: "#ffffff"
  image: dev_assets/images/icon_white_bg.png
  color_dark: "#000000"
  image_dark: dev_assets/images/icon_black_bg.png
  fullscreen: true

flutter:
  uses-material-design: true
  assets:
    - assets/stock_chart/depth.json
    - assets/chart_datatable/quarterly_result.json
