name: number_trivia
description: Number Trivia module.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Service locator
  get_it: ^7.1.3
  # Bloc for state management
  flutter_bloc: ^7.0.0
  # Value equality
  equatable: ^2.0.2
  # Functional programming thingies
  dartz: ^0.9.1
  # Remote API
  data_connection_checker: ^0.3.4
  # Local cache
  shared_preferences: ^2.0.5

  common_ui:
    path: ../common_ui
  showcase_view:
    path: ../showcase_view  

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.8
  bloc_test: ^8.0.0
  pedantic:

flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.fluwix.number_trivia
    iosBundleIdentifier: com.fluwix.numberTrivia
